/**
 * Saved ShredIntel reports — the "keep the conversation + graphs" layer.
 *
 * A voice (or ask) session produces ReportCards (spoken question → answer +
 * Vega chart + the rows behind it, plus an optional drill filter). We persist
 * those per-bot in localStorage so a manager can save-for-later, reopen, and
 * share (download a self-contained HTML report, draft an email, or copy). Demo-
 * grade on purpose: no backend, no PII beyond what /api already scrubbed.
 */

export interface DrillFilter {
  dim: 'section' | 'pinchpoint' | 'sentiment'
  value: string
  label: string
}

export interface ReportCard {
  question: string
  answer: string
  vegaLite?: Record<string, unknown> | null
  rows: Record<string, unknown>[]
  drill?: DrillFilter | null
}

export interface SavedReport {
  id: string
  botId: number
  persona: string
  title: string
  createdAt: number
  cards: ReportCard[]
}

const key = (botId: number) => `shredintel_saved_reports_${botId}`
const MAX = 40

export function newReportId(): string {
  return `r_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`
}

export function listSavedReports(botId: number): SavedReport[] {
  try {
    const raw = localStorage.getItem(key(botId))
    const arr = raw ? JSON.parse(raw) : []
    return Array.isArray(arr) ? (arr as SavedReport[]) : []
  } catch {
    return []
  }
}

export function saveReport(r: SavedReport): void {
  try {
    const all = listSavedReports(r.botId).filter((x) => x.id !== r.id)
    all.unshift(r)
    localStorage.setItem(key(r.botId), JSON.stringify(all.slice(0, MAX)))
  } catch {
    /* localStorage full/unavailable — non-fatal in a demo */
  }
}

export function deleteSavedReport(botId: number, id: string): void {
  try {
    localStorage.setItem(key(botId), JSON.stringify(listSavedReports(botId).filter((x) => x.id !== id)))
  } catch {
    /* */
  }
}

// ── Export / share helpers ────────────────────────────────────────────────

function fmtDate(ts: number): string {
  try {
    return new Date(ts).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })
  } catch {
    return ''
  }
}

function esc(s: unknown): string {
  return String(s ?? '').replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[m] as string)
}

export function reportPlainText(r: SavedReport): string {
  const lines: string[] = [`ShredIntel report — ${r.title}`, `${fmtDate(r.createdAt)} · voice: ${r.persona}`, '']
  r.cards.forEach((c, i) => {
    if (c.question) lines.push(`Q${i + 1}. ${c.question}`)
    if (c.answer) lines.push(c.answer)
    lines.push('')
  })
  lines.push('— Generated by ShredIntel · GetSkiBots')
  return lines.join('\n')
}

function rowsTable(rows: Record<string, unknown>[]): string {
  if (!rows || rows.length === 0) return ''
  const cols = Object.keys(rows[0]).slice(0, 6)
  const head = cols.map((c) => `<th>${esc(c)}</th>`).join('')
  const body = rows
    .slice(0, 20)
    .map((row) => `<tr>${cols.map((c) => `<td>${esc(row[c])}</td>`).join('')}</tr>`)
    .join('')
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
}

/** Self-contained HTML — opens/prints anywhere, no dependencies. */
export function reportToHtml(r: SavedReport): string {
  const cards = r.cards
    .map(
      (c, i) => `
    <section class="card">
      ${c.question ? `<div class="q">Q${i + 1}. ${esc(c.question)}</div>` : ''}
      <p class="a">${esc(c.answer)}</p>
      ${rowsTable(c.rows)}
    </section>`,
    )
    .join('')
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ShredIntel — ${esc(r.title)}</title>
  <style>
    body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#354052;max-width:760px;margin:40px auto;padding:0 20px;line-height:1.55}
    h1{font-size:22px;margin:0 0 4px;color:#3A3F62}
    .meta{color:#616581;font-size:13px;margin-bottom:24px}
    .card{border:1px solid #E2E8F0;border-radius:14px;padding:18px 20px;margin:0 0 16px}
    .q{color:#2182BF;font-weight:600;font-size:13px;margin-bottom:6px}
    .a{font-size:15px;margin:0 0 12px}
    table{border-collapse:collapse;width:100%;font-size:13px}
    th,td{border:1px solid #E2E8F0;padding:6px 10px;text-align:left}
    th{background:#F4F7FA;color:#616581}
    footer{color:#94A3B8;font-size:12px;margin-top:28px}
  </style></head>
  <body>
    <h1>ShredIntel — ${esc(r.title)}</h1>
    <div class="meta">${esc(fmtDate(r.createdAt))} · voice: ${esc(r.persona)}</div>
    ${cards}
    <footer>Generated by ShredIntel · GetSkiBots</footer>
  </body></html>`
}

export function downloadReport(r: SavedReport): void {
  try {
    const blob = new Blob([reportToHtml(r)], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `shredintel-${(r.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'report').slice(0, 40)}.html`
    document.body.appendChild(a)
    a.click()
    a.remove()
    setTimeout(() => URL.revokeObjectURL(url), 2000)
  } catch {
    /* */
  }
}

/** mailto: draft — opens the manager's own mail client; THEY hit send. */
export function mailtoForReport(r: SavedReport): string {
  const subject = `ShredIntel report — ${r.title}`
  const body = reportPlainText(r).slice(0, 1600)
  return `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
}

export async function copyReportSummary(r: SavedReport): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(reportPlainText(r))
    return true
  } catch {
    return false
  }
}
